### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by benqteamilk** [tianshaojie/AndroidFine#23]
我的android studio为2.0，sdk 为6.0.修改了工程的build.gradle的参数，如下： classpath 'com.android.tools.build:gradle:2.0.0'；修改了项目的build.gradle的参数，如下：
    compileSdkVersion 23
    buildToolsVersion '23.0.3'
    targetSdkVersion 23
    compile 'com.android.support:appcompat-v7:23.4.0'
编译，安装到模拟器中，出现了内存泄漏的图标。 
内存泄漏的图标双击，没有任何内容提示。

**Comment by tianshaojie** [comment]
安装app就会显示内存泄漏图标
