### ISSUE TITLE
Tab切换导致的显示问题

### ISSUE THREAD

**Issue by solaris0403** [tianshaojie/AndroidFine#6]
![screenshot_2015-08-25-16-11-00](https://cloud.githubusercontent.com/assets/9546937/9461906/8410fdd8-4b44-11e5-9fa0-76d3e8fcb457.png)
由于没有太仔细看源码，也不知道内部是怎么实现的。不过个人猜测应该是Fragment的显示和隐藏出现问题。
首先在首页Tab中尽可能多的切换上面的几个界面，并刷新。之后再切换下面的Tab，便有了这个问题。

**Comment by tianshaojie** [comment]
你的是什么机型，Android什么版本。我在4.4上按照你说的步骤没试出来。
怀疑是fragment的背景透明引起的
也可能是你说的原因

**Comment by solaris0403** [comment]
三星 GT-I9300   Android:4.1.2
刚才操作了下，应该是透明背景引起的。

**Comment by tianshaojie** [comment]
嗯，我找个4.1.2的机器试试

**Comment by tianshaojie** [comment]
activity_main.xml->FrameLayout增加了background
我这只能找虚拟机试，还是没重现你的问题
可否更新代码运行看看

**Comment by wongdaiv** [comment]
和楼上同样的问题  下载的是  github 上给的apk  应该没有及时更新

**Comment by tianshaojie** [comment]
APK文件已更新，再试试看

**Comment by wongdaiv** [comment]
嗯   这个没问题了 。

**Comment by tianshaojie** [comment]
可以关闭了，哈哈
