### ISSUE TITLE
fragment重叠问题

### ISSUE THREAD

**Issue by jp1017** [tianshaojie/AndroidFine#8]
## mi2A真机出现问题：

<img src ="http://7xlah4.com1.z0.glb.clouddn.com/Screenshot_2015-09-11-20-18-40.png" width = "320"/> <img src ="http://7xlah4.com1.z0.glb.clouddn.com/Screenshot_2015-09-11-20-18-46.png" width = "320"/>

**Comment by d0ng13** [comment]
Fragment切换事务的时候，考虑先hide该group中的所有，然后再看看需要show哪个，问题就有所缓解。如果需要常用这个组件，可以考虑写个Adapter，网上有很多这种类似tab式的Adapter

**Comment by ronanhardiman** [comment]
hide该group中的所有，然后再看看需要show哪个
这个靠谱,用过.

**Comment by crazyqiang** [comment]
我装了一下也有重叠问题  一般是按下home键  打开别的APP  过一段时间再返回  有挺高的几率页面重叠   应该是因为  Activity非正常消失但是fragment被保存的原因   确实存在这个问题

**Comment by jp1017** [comment]
@crazyqiang 是的，请问你怎么解决的?

原因就是后台fragement被杀死，但是activity还保留实例，返回前台出现重叠

**Comment by jp1017** [comment]
@crazyqiang 
@cndongle 
@ronanhardiman 
@tianshaojie 
我已经找到了解决方法：https://www.zhihu.com/question/39662488/answer/82469372

**Comment by tianshaojie** [comment]
@jp1017 代码已更新解决了这个问题

**Comment by liulinjie1990823** [comment]
public void performSelectItem(int hideItem, int showItem, boolean isOnCreate) {
        // 获得将要显示页的tag
        String currentTag = "fragment" + hideItem;
        // 隐藏当前的的fragment
        FragmentTransaction transaction = mFragmentManager.beginTransaction();
        // 如果被杀后再进来，全部的fragment都会被呈现显示状态，所以都隐藏一边
        if (isOnCreate && mFragmentManager.getFragments() != null) {
            for (Fragment fragment : mFragmentManager.getFragments()) {
                transaction.hide(fragment);
            }
        } else {
            // 正常按钮点击进入
            Fragment lastFragment = mFragmentManager.findFragmentByTag(currentTag);
            if (lastFragment != null) {
                transaction.hide(lastFragment);
            }
        }
        // 获得将要显示页的tag
        String toTag = "fragment" + showItem;
        // find要显示的Fragment
        mCurrentFragment = mFragmentManager.findFragmentByTag(toTag);
        if (mCurrentFragment != null) {
            // 已经存在则显示
            transaction.show(mCurrentFragment);
        } else {
            // 不存在则添加新的fragment
            mCurrentFragment = makeFragment(showItem);
            if (mCurrentFragment != null) {
                transaction.add(getFragmentId(), mCurrentFragment, toTag);
            }
        }
        // 选择image图片
        setSelectImage(showItem);
        // 保存当前显示fragment的item
        mHideItem = hideItem;
        mShowItem = showItem;
        transaction.commitAllowingStateLoss();
    }

  @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        outState.putInt("mHideItem", mHideItem);
        outState.putInt("mShowItem", mShowItem);
        LogUtil.e(TAG, "onSaveInstanceState");
    }

  @Override
    public void findViews(Bundle savedInstanceState) {
        super.findViews(savedInstanceState);
        mFragmentManager = getSupportFragmentManager();
        // 从savedInstanceState获取到保存的mCurrentItem
        if (savedInstanceState != null) {
            mHideItem = savedInstanceState.getInt("mHideItem", 0);
            mShowItem = savedInstanceState.getInt("mShowItem", 0);
        }
        // 第一次进入默认显示第1页
        performSelectItem(mHideItem, mShowItem, true);
    }
